### ISSUE TITLE
ng-drag changes ignored

### ISSUE THREAD

**Issue by paschty** [fatlinesofcode/ngDraggable#115]
If ng-drag changes to false the Element is still draggable. If you initialize a element with ng-drag false and then change it to true it doesnt become draggable.

[example](http://jsbin.com/yolenugiku/1/edit?html,css,js,output)

**Comment by cdauth** [comment]
This applies as well to ng-drop.

The reason for this is that the attributes are parsed using `attrs.$observe()` instead of `$scope.$watch()`. This means that changes are only recognised when the actual value of the attribute DOM node changes, but not when the value that it refers to changes.

This means that a workaround is to use curly braces:
```html
<div ng-drag="{{draggable}}"></div>
```

This will be changed by angular to `ng-drag="true"` or `ng-drag="false"`, depending if the variable is true or false. ngDraggable then detects the change, as the value of the attribute node is actually changing.

**Comment by paschty** [comment]
In my example i use ng-drag="{{canDrag[element]}}" and it still doesn´t work. 
It works initial, but if you change the value in the canDrag array, nothing happens.

**Comment by cdauth** [comment]
Ah, interesting. It turns out that what I described only applies to ng-drop, whereas in ng-drag the implementation correctly uses $scope.$watch(). So for ng-drag you must omit the curly braces:
```html
<span ng-drag="canDrag[element]" ng-drag-data="element">{{element}}</span>
```

**Comment by paschty** [comment]
If I remove the curly braces it work... thank you. 
I think it would be good if only one of 'attrs.$observe()' and '$scope.$watch()' would be used, for better consistency.

**Comment by cdauth** [comment]
Any reason why this is closed?
