### ISSUE TITLE
ng-drag-move fires at all drop zones

### ISSUE THREAD

**Issue by bortexz** [fatlinesofcode/ngDraggable#204]
Hi!

I've been trying this library, and I have a little problem with this question.

What I want to achieve is reordering, BUT i want to make the reorder before you need to drop (So listening to ng-drag-move). I have the elements as the same drop zones. I've also tried to have the draggable element as a child of the drop zone.

My problem is, ng-drag-move fires for all of the drop-zones, instead of the one where the object is moving over. Is there a bug or the expected behaviour? If it's the last, then how you would achieve what a want to do? Is it possible with this library?

Thanks for help!

**Comment by DmitriiSer** [comment]
All you need is "ng-drag-enter" and "ng-drag-leave". But they are still waiting to be pulled from [Add ng-drag-enter and ng-drag-leave attributes and events #141](https://github.com/fatlinesofcode/ngDraggable/pull/141). Since it's been awhile when this pull request was created (Apr 21, 2015) I'd suggest to change your "ngDraggable.js" file by yourself with improvements from this commit and play with that. Now you don't need "ng-drag-move", just use "ng-drag-enter" with $index parameter and you'll always know what drop zone you are entering.

You could find the modified "ngDraggable.js" at my repo **[here](https://github.com/DmitriiSer/Lister)**.

And you could see how it works on a real example **[here](http://lister-advancedlists.rhcloud.com)**.
###### NOTE: I have another issue: when I reorder the list of droppable elements while dragging an element through them it seems the position of draggable element under the cursor calculates relatively from the current position of the starting-droppable element. And since I reorder droppable elements on "ng-drag-enter" this starting-sroppable element change it's position in the list so does and it creates a weird position glitch. You could see it in my [demo](http://lister-advancedlists.rhcloud.com)
