### ISSUE TITLE
<select> tag inside  ngDraggable

### ISSUE THREAD

**Issue by madhav5589** [fatlinesofcode/ngDraggable#42]
I go through the issue #12 and I tried the same logic but it's not working. So, want to ask that how can I use dropdown menu within ngDraggable. I used ng-prevent-drag directive and it allow me to click on dropdown but it doesn't populate the options. 
Any suggestions ?
Thanks

**Comment by paschty** [comment]
The provided example does not work with the newest version of ngDraggable.
I cannot use the select boxes.
Tested in Chrome 41 and Firefox 31.4.0.

The solution with ng-cancel-drag is not realy good, because children which use select or input need to know that they are wrapped in a draggable element.
The directive should ignore input and select elements instead.
